### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by afc163** [gzgogo/antd-theme#1]
- [x] antd 版本建议升级到最新。默认主题下危险按钮的样式是老的：https://ant.design/changelog-cn#3.20.4
- [ ] 切换主题时，url 最好跟着一起变化。
- [x] 阿里云主题的圆角不太对。
- [x] 界面上提供明显的 GitHub 入口。

**Comment by afc163** [comment]
- [ ] `Antd` 是错误拼写：https://ant.design/docs/react/faq-cn#%E5%A6%82%E4%BD%95%E6%AD%A3%E7%A1%AE%E7%9A%84%E6%8B%BC%E5%86%99-Ant-Design%EF%BC%9F

**Comment by afc163** [comment]
- [ ] www.antdtheme.com 和 antdtheme.com 不太一样，貌似不是同一个版本。

**Comment by akaguny** [comment]
pls rewrite ob English @afc163

**Comment by gzgogo** [comment]
@akaguny done

**Comment by gzgogo** [comment]
【切换主题时，url 最好跟着一起变化】该问题由于和存储的逻辑有一些冲突，暂时没有修改

**Comment by gzgogo** [comment]
【切换主题时，url 最好跟着一起变化】该问题由于和存储的逻辑有一些冲突，暂时没有修改 @afc163

**Comment by afc163** [comment]
> 【切换主题时，url 最好跟着一起变化】该问题由于和存储的逻辑有一些冲突，暂时没有修改 @afc163

这样就没有独立 url 可以看各个主题了。
