### ISSUE TITLE
How to run locally?

### ISSUE THREAD

**Issue by romu70** [gzgogo/antd-theme#13]
Hi, is there a guide or documentation about how to run this app locally?

My main problem is I didn't find any way to create a theme gradually, step by step, this means being able to work on it for a moment, then doing something else and get back to the theme creation later.

Thanks.

**Comment by luclemo** [comment]
Same question here… would ne nice to have a couple lines in the readme for this.
Thanks

**Comment by romu70** [comment]
Clone this repo, open a terminal and:

1. npm i
2. npm start

Enjoy!
