### ISSUE TITLE
不知道怎么用......

### ISSUE THREAD

**Issue by fengnex** [gzgogo/antd-theme#16]
1. Visit antdtheme.com，Click "Save" after editing is complete
3. Import and add your theme in the file: theme/index.js. The key is the name of your theme in the list.

按首页上的说明，在antdtheme.com上花了很多时间才发现Save在右下角，搞不清楚该怎么用，能否简要地说说？

按这个项目首页上说的，上面第3步之后，怎么预览、验证自己修改的效果呢？特别是按首页文档添加了几个theme之后，哪里设置真正用那个theme？

**Comment by swiftwind0405** [comment]
同没搞懂。。

**Comment by gzgogo** [comment]
这个方案的原理就是导出一堆less变量，在你的项目中覆盖默认的变量值来达到修改主题的目的。
预览是实时的，修改卡片里的变量后，会实时在页面中反馈，整个修改完毕后，可以通过点击右下角的“Save”按钮来生成less或js文件，然后将这两个文件之一(依赖你项目的配置情况)导入到你的项目里，覆盖默认的变量

**Comment by fengnex** [comment]
整个2020年都没有更新。。。。。。

**Comment by gzgogo** [comment]
非常抱歉，精力不够啊实在是，欢迎pr共建或着急的话加我微信交流
