### ISSUE TITLE
项目启动报错

### ISSUE THREAD

**Issue by shengbeiniao** [gzgogo/antd-theme#17]
![image](https://user-images.githubusercontent.com/3301995/79331267-7a57b880-7f4d-11ea-9070-43ce051f18fc.png)
样式不能正确加载

**Comment by shuurai** [comment]
Same here, I get the same issue as above when starting.

**Comment by gzgogo** [comment]
console 有报错吗

**Comment by zjfjiayou** [comment]
main.js:269936 Operation on an invalid type

**Comment by huixisheng** [comment]
用 npm  install 安装依赖，不要用 yarn 安装。
